### ISSUE TITLE
error handling incorrect

### ISSUE THREAD

**Issue by chriseppstein** [strarsis/eyeglass-file-text#1]
https://github.com/strarsis/eyeglass-file-text/blob/master/eyeglass-exports.js#L14

instead you should *always* call the `done()` callback with an error object.

```js
 done(sass.types.Error("File read error: \'" + err.toString() + "\'."));
```

**Comment by strarsis** [comment]
Thank you for the report.
It should be fixed now (Release v0.1.0).
